### ISSUE TITLE
Sometimes SSL bombs out

### ISSUE THREAD

**Issue by pjotrp** [pjotrp/biogems.info#72]
Not sure what it is, and it does not happen all the time (so it must be related to timeouts)

/home/wrk/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/openssl/buffering.rb:145:in `sysread_no
nblock': end of file reached (EOFError)
(...)
from /export/local/users/wrk/opt/ruby/biogems.info/lib/biogems/http.rb:31:in `get_https_body' from ./bin/fetch-geminfo.rb:116:in `get_github_commit_stats'

Here it is suggested that it has to do with Ruby 1.9.2

http://stackoverflow.com/questions/12387645/eoferror-end-of-file-reached-on-heroku-while-posting-utf-8-via-ssl

**Comment by pjotrp** [comment]
Upgraded Ruby
